name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pytest pytest-cov bandit pip-audit
      - name: Lint and security
        run: |
          python -m pip install black flake8 isort
          black --check .
          isort --check-only .
          flake8 .
          bandit -r src
          pip-audit --strict
      - name: Tests with coverage
        run: pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml --cov-fail-under=85
      - name: Upload coverage xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
