name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest pytest-cov ruff black isort bandit pip-audit
      - name: Lint (ruff)
        run: ruff check .
      - name: Format (ruff)
        run: ruff format --check
      - name: Black (check)
        run: black --check .
      - name: isort (check)
        run: isort --check-only .
      - name: Security (bandit)
        run: bandit -q -r src
      - name: Security (pip-audit)
        run: pip-audit --strict
      - name: Tests with coverage
        run: pytest --cov=src --cov-report=term-missing --cov-fail-under=85
